config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root 'messages#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy]

	def index
		@messages = Message.all.order("created_at DESC")
	end

	def show
		@message = Message.find(params[:id])
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)

		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to root_path
	end

	private 

	def message_params
		params.require(:message).permit(:title, :description)
	end

	def find_message
		@message = Message.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Espn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<div class="md-col-8 col-md-offset-2">
	<h2 class="new-msg-header">Edit Message</h2>
	<%= render 'form' %>
</div>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
	<div class="col-md-10 col-md-offset-1">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "Join to conversation", message, class: "btn-custom" %>
		</div>
	</div>
<% end %>

<%= link_to "Post Message", new_message_path %>

app/views/messages/new.html.erb
<div class="md-col-8 col-md-offset-2">
	<h2 class="new-msg-header">Post Message</h2>
	<%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by"><%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-desc"><%= @message.description %></p>
		<div class="links btn-group">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
			<%= link_to "Edit", edit_message_path(@message), class: "btn btn-primary" %>
			<%= link_to "Delete", message_path(@message), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
		</div>
	</div>
</div>